default-tasks:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  tasks:
    com.palantir.distgo:dist-plugin:
      assets:
        - locator:
            id: com.palantir.godel-distgo-asset-dist-golangci-lint:dist-golangci-lint-asset:0.5.0
            checksums:
              darwin-amd64: b9dd6bd503b76f04342071b737a77f62f9bda60300bfd295b7439bfeaac9ca27
              darwin-arm64: 4526e7dbcafa7c682fd3df1cfe2b22da4da6180dce04e123bb444d8a7aa4648c
              linux-amd64: c48173a7aaa403b6ecfa89c93577451e2e6466135b3f04088b0347a5d5cf6b11
              linux-arm64: 36ed9d30785dc2eecb07099649bc1108c67102cc53c3c19b845d98db97cb8bda
plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.49.0
        checksums:
          darwin-amd64: 704707521a1c7b9876b2f1be59e6efd01035a6af1dd39d201a560a7d1f4d436c
          darwin-arm64: 486364b17b2d352ed8532e29d2c5d69e607997db4531e63ad6632aeb77846a13
          linux-amd64: 239d8c56431e15fa71e4cc2a8ee5cd562cf38264b146587155423283ae205b90
          linux-arm64: c27790f0a843935c4cc44bace1b4b6cf770213727ed86a96740e7fe875dd5121
environment:
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - "\\..+"
    - "vendor"
  paths:
    - "godel"
