default-tasks:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  tasks:
    com.palantir.distgo:dist-plugin:
      assets:
        - locator:
            id: com.palantir.godel-distgo-asset-dist-golangci-lint:dist-golangci-lint-asset:0.10.0
            checksums:
              darwin-amd64: e3b569224005cc92f0f11ff24b2e309d61266c3a0c16e39bb57434972ff8326e
              darwin-arm64: b4eb67a5ebaf00f950a7ae27db3003647172f593e3c14b4693aaa2ac7041363f
              linux-amd64: cb248f8f040278310e1e543f98ceb307682ea74c4d6b70c2c1a3a829a294a89b
              linux-arm64: 6262fae33fe05b705abc3a72dcad98cab66b27f503b354ad41d13841f974aa86
plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.54.0
        checksums:
          darwin-amd64: 71c895d2c8175ac74884fdd81c24d387ef695508798ad117b19c57957d657446
          darwin-arm64: 69b1bd3a93655510a21212645a7bbcabd01cacc9c033c1443fe2bd90171a7cb5
          linux-amd64: ee8992369ffafb909481b9cb641d9cf783b1d82ab2c4ffd576b21bde44978810
          linux-arm64: 621f372fdebe9e96d2052ebee42406b9074f3a4ad773591abc88e6655e05b785
environment:
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - "\\..+"
    - "vendor"
  paths:
    - "godel"
